version: '3.1'
services:
  mysql:
    image: mysql:8.0.26
    restart: 'always'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true' # TODO: Change this
      MYSQL_USER: 'username'
      MYSQL_PASS: 'password'
      MYSQL_DATABASE: 'f1_manager'
    ports:
      - '3306:3306'
#    volumes:
#      - my-datavolume:/var/lib/mysql
# volumes:
#  my-datavolume: